custom: 
  lambda_name: bsGetPatientProfile 
  lambda_role: LambdaAccessLambda 
  lambda_description: Recuperar dados cadastrais de um paciente
  lambda_runtime: nodejs8.10 
  lambda_memory: ${file(../variables.json):lambda_memory} 
  lambda_timeout: ${file(../variables.json):lambda_timeout} 
  arn_hash: ${file(../variables.json):arn_hash} 
  
service: ${self:custom.lambda_name} 
  
provider: 
  name: aws 
  stackName: ${self:custom.lambda_name} 
  runtime: ${self:custom.lambda_runtime} 
  role: arn:aws:iam::${self:custom.arn_hash}:role/${self:custom.lambda_role} 
  
functions: 
  func: 
    handler: index.handler 
    name: ${self:custom.lambda_name} 
    memorySize: ${self:custom.lambda_memory} 
    timeout: ${self:custom.lambda_timeout} 
    description: ${self:custom.lambda_description} 
    tags: 
      api: Prontuario 
    package: 
      exclude: 
        - node_modules/** 
        - test/** 